// Package autogen provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.4.1 DO NOT EDIT.
package autogen

import (
	"bytes"
	"compress/gzip"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
	strictecho "github.com/oapi-codegen/runtime/strictmiddleware/echo"
)

const (
	OauthClientScopes = "oauthClient.Scopes"
	SessionScopes     = "session.Scopes"
)

// Defines values for OAuthAuthorizationCodeTokenRequestGrantType.
const (
	OAuthAuthorizationCodeTokenRequestGrantTypeAuthorizationCode OAuthAuthorizationCodeTokenRequestGrantType = "authorization_code"
)

// Defines values for OAuthAuthorizationErrorCode.
const (
	OAuthAuthorizationErrorCodeAccessDenied            OAuthAuthorizationErrorCode = "access_denied"
	OAuthAuthorizationErrorCodeInvalidRequest          OAuthAuthorizationErrorCode = "invalid_request"
	OAuthAuthorizationErrorCodeInvalidScope            OAuthAuthorizationErrorCode = "invalid_scope"
	OAuthAuthorizationErrorCodeServerError             OAuthAuthorizationErrorCode = "server_error"
	OAuthAuthorizationErrorCodeTemporarilyUnavailable  OAuthAuthorizationErrorCode = "temporarily_unavailable"
	OAuthAuthorizationErrorCodeUnauthorizedClient      OAuthAuthorizationErrorCode = "unauthorized_client"
	OAuthAuthorizationErrorCodeUnsupportedResponseType OAuthAuthorizationErrorCode = "unsupported_response_type"
)

// Defines values for OAuthClientCredentialTokenRequestGrantType.
const (
	OAuthClientCredentialTokenRequestGrantTypeAuthorizationCode OAuthClientCredentialTokenRequestGrantType = "authorization_code"
)

// Defines values for OAuthScope.
const (
	Address               OAuthScope = "address"
	ClubMembers           OAuthScope = "club_members"
	ClubMembersAdminRead  OAuthScope = "club_members:admin_read"
	ClubMembersAdminWrite OAuthScope = "club_members:admin_write"
	ClubMembersWrite      OAuthScope = "club_members:write"
	ClubRolesAdminWrite   OAuthScope = "club_roles:admin_write"
	ClubRolesWrite        OAuthScope = "club_roles:write"
	Clubs                 OAuthScope = "clubs"
	ClubsAdminWrite       OAuthScope = "clubs:admin_write"
	Email                 OAuthScope = "email"
	Openid                OAuthScope = "openid"
	Phone                 OAuthScope = "phone"
	Profile               OAuthScope = "profile"
	UserinfoAdminRead     OAuthScope = "userinfo:admin_read"
	UserinfoAdminWrite    OAuthScope = "userinfo:admin_write"
)

// Defines values for OAuthTokenEndpointErrorCode.
const (
	OAuthTokenEndpointErrorCodeInvalidClient        OAuthTokenEndpointErrorCode = "invalid_client"
	OAuthTokenEndpointErrorCodeInvalidGrant         OAuthTokenEndpointErrorCode = "invalid_grant"
	OAuthTokenEndpointErrorCodeInvalidRequest       OAuthTokenEndpointErrorCode = "invalid_request"
	OAuthTokenEndpointErrorCodeInvalidScope         OAuthTokenEndpointErrorCode = "invalid_scope"
	OAuthTokenEndpointErrorCodeUnauthorizedClient   OAuthTokenEndpointErrorCode = "unauthorized_client"
	OAuthTokenEndpointErrorCodeUnsupportedGrantType OAuthTokenEndpointErrorCode = "unsupported_grant_type"
)

// Defines values for OIDCResponseType.
const (
	OIDCCodeResponseType    OIDCResponseType = "code"
	OIDCIdTokenResponseType OIDCResponseType = "id_token"
	OIDCNoneResponseType    OIDCResponseType = "none"
	OIDCTokenResponseType   OIDCResponseType = "token"
)

// Defines values for TokenType.
const (
	Bearer TokenType = "Bearer"
)

// OAuthAccessToken defines model for OAuthAccessToken.
type OAuthAccessToken = string

// OAuthAuthorizationCode Authorization code that can be used to retrieve tokens
type OAuthAuthorizationCode = string

// OAuthAuthorizationCodeTokenRequest Request an access token with an authorization code ([spec](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.3))*
type OAuthAuthorizationCodeTokenRequest struct {
	// Code Authorization code that can be used to retrieve tokens
	Code      OAuthAuthorizationCode                      `json:"code" bson:"code"`
	GrantType OAuthAuthorizationCodeTokenRequestGrantType `json:"grant_type" bson:"grant_type"`

	// RedirectUri The callback URI that was used for the authorization request
	RedirectUri string `json:"redirect_uri" bson:"redirect_uri"`
}

// OAuthAuthorizationCodeTokenRequestGrantType defines model for OAuthAuthorizationCodeTokenRequest.GrantType.
type OAuthAuthorizationCodeTokenRequestGrantType string

// OAuthAuthorizationErrorCode Authorization endpoint error code as defined in section 4.1.2.1 of [RFC6749](https://datatracker.ietf.org/doc/html/rfc6749#section-4.1.2.1)
type OAuthAuthorizationErrorCode string

// OAuthClientCredentialTokenRequest Request an access token using client credentials *([spec](https://datatracker.ietf.org/doc/html/rfc6749#section-4.4.2))*
type OAuthClientCredentialTokenRequest struct {
	GrantType OAuthClientCredentialTokenRequestGrantType `json:"grant_type" bson:"grant_type"`
	Scope     *[]OAuthScope                              `json:"scope,omitempty" bson:"scope"`
}

// OAuthClientCredentialTokenRequestGrantType defines model for OAuthClientCredentialTokenRequest.GrantType.
type OAuthClientCredentialTokenRequestGrantType string

// OAuthClientId defines model for OAuthClientId.
type OAuthClientId = uint64

// OAuthRefreshToken defines model for OAuthRefreshToken.
type OAuthRefreshToken = string

// OAuthScope Describes the scopes that can be granted using OAuth.
//
// Most scopes are read-only by default, and can be appended with `:write` to get write pemission,
// `:admin_read` to get admin read permission (e.g. read others private information), or `:admin_write`
// to get admin write permission (e.g. edit other user's information).
//
// Scopes appended with `:admin_read` or `:admin_write` are usually linked to administrative permissions,
// and will likely require reauthentication of the end-user, and that the end-user uses advanced authentication
// features such as 2FA. If the end-user does not have access to the associatd permission, the scope will
// be ignored for the Authentication Request, and will not be shown in the consent screen.
//
// Scopes related to club management permissions (e.g. `club_members:write`) will be shown in the consent
// screen even if the end user does not currently have such permissions. This avoids the need for the client
// to renew its authorization request if the user was to gain or loose such privileges in the future
// (e.g. registering to a club management application before being assigned the club roles). Note that club
// management permissions are checked every time a management request is made, and the server does not take
// that the presence of the scopes in the access token for a proof tht the end user has the permissions, applications
// need to handle 403 Forbidden errors on these endpoints accordingly.
type OAuthScope string

// OAuthTokenEndpointErrorCode Token endpoint error code as defined in section 5.2 of [RFC6749](https://datatracker.ietf.org/doc/html/rfc6749#section-5.2)
type OAuthTokenEndpointErrorCode string

// OIDCResponseType OpenID Connect `response_type`
type OIDCResponseType string

// TokenType Type of token to use for authentication. Currently, only "Bearer" is supported.
type TokenType string

// StartAuthorizationFlowParams defines parameters for StartAuthorizationFlow.
type StartAuthorizationFlowParams struct {
	// ResponseType Type(s) of oauth response expected, comma-separated. `none` cannot be used with other response types.
	//
	// See [specification](https://openid.net/specs/oauth-v2-multiple-response-types-1_0.html#Combinations) for allowed combinations.
	ResponseType []OIDCResponseType `form:"response_type" json:"response_type" bson:"response_type"`
	ClientId     OAuthClientId      `form:"client_id" json:"client_id" bson:"client_id"`
	RedirectUri  string             `form:"redirect_uri" json:"redirect_uri" bson:"redirect_uri"`

	// Scope Scopes to request to the end user. MUST include the `openid` scope
	Scope []OAuthScope `form:"scope" json:"scope" bson:"scope"`

	// State Opaque value that will be returned to the redirect URI as a query parameter if present.
	//
	// It SHOULD be used to [prevent CSRF attacks](https://datatracker.ietf.org/doc/html/rfc6749#section-10.12)
	State *string `form:"state,omitempty" json:"state,omitempty" bson:"state"`

	// Nonce Opaque value that will be embeded in the `id_token`, to mitigate replay attacks.
	//
	// See [OIDC spec](https://openid.net/specs/openid-connect-core-1_0.html#NonceNotes) for more informations
	Nonce *string `form:"nonce,omitempty" json:"nonce,omitempty" bson:"nonce"`
}

// IssueOauthTokenFormdataBody defines parameters for IssueOauthToken.
type IssueOauthTokenFormdataBody struct {
	union json.RawMessage `bson:"union"`
}

// IssueOauthTokenFormdataRequestBody defines body for IssueOauthToken for application/x-www-form-urlencoded ContentType.
type IssueOauthTokenFormdataRequestBody IssueOauthTokenFormdataBody

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /health)
	GetHealth(ctx echo.Context) error
	// Start an OAuth flow
	// (GET /oauth/authorize)
	StartAuthorizationFlow(ctx echo.Context, params StartAuthorizationFlowParams) error
	// OAuth token endpoint
	// (POST /oauth/token)
	IssueOauthToken(ctx echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface `bson:"handler"`
}

// GetHealth converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealth(ctx echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealth(ctx)
	return err
}

// StartAuthorizationFlow converts echo context to params.
func (w *ServerInterfaceWrapper) StartAuthorizationFlow(ctx echo.Context) error {
	var err error

	ctx.Set(SessionScopes, []string{})

	// Parameter object where we will unmarshal all parameters from the context
	var params StartAuthorizationFlowParams
	// ------------- Required query parameter "response_type" -------------

	err = runtime.BindQueryParameter("form", false, true, "response_type", ctx.QueryParams(), &params.ResponseType)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter response_type: %s", err))
	}

	// ------------- Required query parameter "client_id" -------------

	err = runtime.BindQueryParameter("form", true, true, "client_id", ctx.QueryParams(), &params.ClientId)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter client_id: %s", err))
	}

	// ------------- Required query parameter "redirect_uri" -------------

	err = runtime.BindQueryParameter("form", true, true, "redirect_uri", ctx.QueryParams(), &params.RedirectUri)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter redirect_uri: %s", err))
	}

	// ------------- Required query parameter "scope" -------------

	err = runtime.BindQueryParameter("form", false, true, "scope", ctx.QueryParams(), &params.Scope)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter scope: %s", err))
	}

	// ------------- Optional query parameter "state" -------------

	err = runtime.BindQueryParameter("form", true, false, "state", ctx.QueryParams(), &params.State)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter state: %s", err))
	}

	// ------------- Optional query parameter "nonce" -------------

	err = runtime.BindQueryParameter("form", true, false, "nonce", ctx.QueryParams(), &params.Nonce)
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter nonce: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.StartAuthorizationFlow(ctx, params)
	return err
}

// IssueOauthToken converts echo context to params.
func (w *ServerInterfaceWrapper) IssueOauthToken(ctx echo.Context) error {
	var err error

	ctx.Set(OauthClientScopes, []string{})

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.IssueOauthToken(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithBaseURL(router, si, "")
}

// Registers handlers, and prepends BaseURL to the paths, so that the paths
// can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(baseURL+"/health", wrapper.GetHealth)
	router.GET(baseURL+"/oauth/authorize", wrapper.StartAuthorizationFlow)
	router.POST(baseURL+"/oauth/token", wrapper.IssueOauthToken)

}

type GetHealthRequestObject struct {
}

type GetHealthResponseObject interface {
	VisitGetHealthResponse(w http.ResponseWriter) error
}

type GetHealth200Response struct {
}

func (response GetHealth200Response) VisitGetHealthResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type StartAuthorizationFlowRequestObject struct {
	Params StartAuthorizationFlowParams `bson:"params"`
}

type StartAuthorizationFlowResponseObject interface {
	VisitStartAuthorizationFlowResponse(w http.ResponseWriter) error
}

type StartAuthorizationFlow200Response struct {
}

func (response StartAuthorizationFlow200Response) VisitStartAuthorizationFlowResponse(w http.ResponseWriter) error {
	w.WriteHeader(200)
	return nil
}

type StartAuthorizationFlow302Response struct {
}

func (response StartAuthorizationFlow302Response) VisitStartAuthorizationFlowResponse(w http.ResponseWriter) error {
	w.WriteHeader(302)
	return nil
}

type IssueOauthTokenRequestObject struct {
	Body *IssueOauthTokenFormdataRequestBody `bson:"body"`
}

type IssueOauthTokenResponseObject interface {
	VisitIssueOauthTokenResponse(w http.ResponseWriter) error
}

type IssueOauthToken200JSONResponse struct {
	AccessToken *OAuthAccessToken `json:"access_token,omitempty" bson:"access_token"`

	// ExpiresIn Lifetime in seconds of the access token
	ExpiresIn    *uint32            `json:"expires_in,omitempty" bson:"expires_in"`
	RefreshToken *OAuthRefreshToken `json:"refresh_token,omitempty" bson:"refresh_token"`

	// Scope The scope of the access token. REQUIRED if its different from the one requested.
	Scope *[]OAuthScope `json:"scope,omitempty" bson:"scope"`

	// TokenType Type of token to use for authentication. Currently, only "Bearer" is supported.
	TokenType *TokenType `json:"token_type,omitempty" bson:"token_type"`
}

func (response IssueOauthToken200JSONResponse) VisitIssueOauthTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)

	return json.NewEncoder(w).Encode(response)
}

type IssueOauthToken400JSONResponse struct {
	// Error Token endpoint error code as defined in section 5.2 of [RFC6749](https://datatracker.ietf.org/doc/html/rfc6749#section-5.2)
	Error OAuthTokenEndpointErrorCode `json:"error" bson:"error"`

	// ErrorDescription Human-readable text that provides more information about the error
	ErrorDescription *string `json:"error_description,omitempty" bson:"error_description"`
}

func (response IssueOauthToken400JSONResponse) VisitIssueOauthTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)

	return json.NewEncoder(w).Encode(response)
}

type IssueOauthToken401JSONResponse struct {
	// Error Token endpoint error code as defined in section 5.2 of [RFC6749](https://datatracker.ietf.org/doc/html/rfc6749#section-5.2)
	Error OAuthTokenEndpointErrorCode `json:"error" bson:"error"`

	// ErrorDescription Human-readable text that provides more information about the error
	ErrorDescription *string `json:"error_description,omitempty" bson:"error_description"`
}

func (response IssueOauthToken401JSONResponse) VisitIssueOauthTokenResponse(w http.ResponseWriter) error {
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)

	return json.NewEncoder(w).Encode(response)
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /health)
	GetHealth(ctx context.Context, request GetHealthRequestObject) (GetHealthResponseObject, error)
	// Start an OAuth flow
	// (GET /oauth/authorize)
	StartAuthorizationFlow(ctx context.Context, request StartAuthorizationFlowRequestObject) (StartAuthorizationFlowResponseObject, error)
	// OAuth token endpoint
	// (POST /oauth/token)
	IssueOauthToken(ctx context.Context, request IssueOauthTokenRequestObject) (IssueOauthTokenResponseObject, error)
}

type StrictHandlerFunc = strictecho.StrictEchoHandlerFunc
type StrictMiddlewareFunc = strictecho.StrictEchoMiddlewareFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface  `bson:"ssi"`
	middlewares []StrictMiddlewareFunc `bson:"middlewares"`
}

// GetHealth operation middleware
func (sh *strictHandler) GetHealth(ctx echo.Context) error {
	var request GetHealthRequestObject

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealth(ctx.Request().Context(), request.(GetHealthRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealth")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetHealthResponseObject); ok {
		return validResponse.VisitGetHealthResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// StartAuthorizationFlow operation middleware
func (sh *strictHandler) StartAuthorizationFlow(ctx echo.Context, params StartAuthorizationFlowParams) error {
	var request StartAuthorizationFlowRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.StartAuthorizationFlow(ctx.Request().Context(), request.(StartAuthorizationFlowRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "StartAuthorizationFlow")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(StartAuthorizationFlowResponseObject); ok {
		return validResponse.VisitStartAuthorizationFlowResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// IssueOauthToken operation middleware
func (sh *strictHandler) IssueOauthToken(ctx echo.Context) error {
	var request IssueOauthTokenRequestObject

	if form, err := ctx.FormParams(); err == nil {
		var body IssueOauthTokenFormdataRequestBody
		if err := runtime.BindForm(&body, form, nil, nil); err != nil {
			return err
		}
		request.Body = &body
	} else {
		return err
	}

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.IssueOauthToken(ctx.Request().Context(), request.(IssueOauthTokenRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "IssueOauthToken")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(IssueOauthTokenResponseObject); ok {
		return validResponse.VisitIssueOauthTokenResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, gzipped, json marshaled Swagger object
var swaggerSpec = []string{

	"H4sIAAAAAAAC/+xabXPbNvL/Khi2M/+4I1F+SPPv6Z3rJK3m2qRnO68sjwyRKwk1CDAAKFnn0Xe/2QXB",
	"B4lyZbt3nZu5V4kpENj97dNvF3yMEp3lWoFyNho+RjZZQMbpv5/PC7c4TxKw9lrfg8Jnbp1DNIysM0LN",
	"o02vXFS4hTbin9wJrS50Crg0BZsYkeOjaBi1lrBEp8DcgjuWcMWmwAoLKXOaGXBGwBKYwxNt1Dv0RJLw",
	"Er4WYN3u6eUPjCvGSSG/P1sJt6CHu9K9ubE5JLdvFs7ldjgYpNxxZ3hyDyYW4GaxNvNBqpPBwmVyYGbJ",
	"u/9/+7dvLCS4Rf9tfBKfHR19F/Wi3OgcjBNAoCYlOt8amEXD6JtBDf+gxH6wB9NNL5obrtzEQ/IYgSqy",
	"aHgTtaSf0Am3HcAZSIWBxE0KI3Yhul4AS7iUU57csy+XI2+eFbfeNjNtmFvAFlKmBLwXwQPPcokHImDD",
	"wUDqhMuFtm74w/EPx4OwddSLZtpk3EXDCOXYkZME/VoIAynq1tC458HbUqTWVE9/h8R1u8gHY7Q5xDNB",
	"pbkWyjHAN7wrcMtSmAkFKROKlSZmaOLT+ITpGbu5/HiB5n+Nt5zGJ0eIY2lToZZcinRSI1yogD2kk0QK",
	"UPjUu/MkBSUgpVW2yHNtHOC7NtfKQoAv7GkTTX9bMEswE9IUDQFZrg03Qq4nheJLLiSfym5fIoQvSIgL",
	"AykoJ7h8WQwWVqg58wqxpNrMsu9eG4Jv49OuEHxVEHnsho+RcJDZgyL5il7ZVJtxY/j6KUff69Ie8FFK",
	"coeAOzk9e/v9u2ZYCeXeva0jSygHczDVLpcwM2AXf5DTr4KibSu+p7+mYCkbEBq2lclJD0hLs9JW8ViN",
	"1a/aurCeG2AGeNrXSq7ZdI3hxQvpeoyrNGzE8xxUCqlP0nfDlREO7rBIzMEx+ovlkAlrhVa9sbob8jQT",
	"aoIbV8voEZ3FcjDlYvYG4nnsn2q3AGNZbsSSO2BCeRiFVkc9pg0Lu/rTx6q1bxBia2NIhfMbY+40/2db",
	"2xIaVyUQWzo2Ndg5nGArbMGlXDMp1L0vmbREWGe4E8umNLY3VojnSkjJpLgHuWalx6HuhVtgpCU+7+kZ",
	"GRRU2keZvSXIrs3HqI9lPF1ylUDK2nuM1Qy4KwxYZotkgWnz9ON5zEbtrVmqwTKlHVvwJdS5wJcXa3Ui",
	"uGuaq1e7GukyVlNgYq60adSl87Y6ZbLxahAAeOAUmF3olcI0ji8lmB0VuqUBUE3DGJDceXwTWUxZxhWf",
	"Q4aLGwCX9r7DJZMMsikYW/rpkT91z4lj5Y9ksATFRAUQawOUFMaAcnLtoSJUG8fH7HohLONLLVIfjwoa",
	"kPiUSi5rQMGKCWe763eQgE7Hko9ezoVCH5Ra23C0EUshYQ42qDMr0N5jFQJqLqwDTCPkmDvQ8TyXwUJT",
	"mGkDbAq4mlsr5lhfvdzFlBktwR7F7JN2gSnKYjpWewyBoZEsIMGYgCWYNXMiA8abp1fKWpbxFIKLA/N1",
	"sIbd8XsYq8r5cwMWVAIhRsokVkLQqmUIPWe50bTUtc264N5IzQhtQmLHiuznNFtwlUpgb4/P2EdtpiJN",
	"0VewTlum6VwLFVWxKIM2qVBzuY7HqsEidA5KpL4CzoTEog8ZFxKJQ5oasMiw84VW+AsKiYmqkYV2n5J3",
	"IxWTxdSW/wbX3/pz2FxbPWxt3vFL6yXygmHHow5hWs/2chaqeh9K5J5ghbTuGWzw+/j0z2CC38enT7PA",
	"8KQigOEB1d29NLFJC1uUus0JO2Ebvb+4LJnk9bqLE3zOQY3eswutFCSO3bV4513LIZV3tZLIU9CgEOnE",
	"//e22UiERS2BetFDHzfrL7lRPENGd0MiftIKWmJ6ydG6HY9LqrrzfJTu/nK76Xl36NYen1JqII9xGoPd",
	"J4JWSYrZRcjmPUa8Zxz9CNyAGUeYkir7xA24/IIOsyAThaQwwq2vkGt6Zqt5RRI7rITuz/yvW7L1tpw6",
	"eHHllqfxWXzyUp+ml9GriRWjFlNuRVKbFrdFTyPxK1raJb2fClQc0+mSZjWzaNSjtDdKS3/8YmQ0jAbx",
	"CqTs3yu9UgOfFvuJVjMxLwy9V4vTeps4P1C27m4dSxSx7oRET2TuJ63nEjwBxjqKv6DDDnJu7UqbtEdE",
	"F5sGCS4snEm9shSWFAD6XqBn4nt43MXF9eTqw9VVLSvPxd8Bm4kNvjPTKKMUCShLnlq++OvoGnMAARFs",
	"iFpaXZgEyHrlS4NMuAH1KsJREGJsn/82Yn128eH6wyd2niS6UA5lXILxsETH8Ul8TBbMQfFcRMPoLD6O",
	"z7C4cLcg3xwsgEu3oAYMyD2xJyPosaGJfgL3s1+BfZEPP3rx9Pi4A/nfRuyzkkJBKxai4c0t/j0gVxpU",
	"mbBxahhE0N6+9R0+Ro/flik2/lqAWcfNEcOm8XbODc/AYbEb3ux2uK4wZQgROzJ8Tsyj6gwDhQjbs8KI",
	"OJibTq6tHdryukl0poAyivjzZ0h1sdtsejt4pqnA/3LZ7FWIxVkrrGsQSpbCEqTOczAx+zeoPGlK1lR3",
	"JwXu4P/hH19Glx/eBzo7jqzjDsYRq8xG7NYTOldx8pInd1LjmLFrJHEPPHFsyWWBmiQglki0jc5wh7Hy",
	"W8QMO4gXQkJlsgsU0uFJIG4PiZjr2oBIWXMX2HYYzG02lEVsQYT2TwuK8wOGvdwndmrARgGbBocgq93h",
	"Pnc9JojBmwbKnJF8tZVj2oardUD6LjAM31aX/22fIfyks+sA6o2MrEy531glZ3lpjO4NzzAzm5QsowPN",
	"0IhgM/zbKO5yxaYOIUi6wUDAS+NDul/dplDPi9VzxYJN2ExLqVfUNS6A3SAPYzaHRMzKml4zD1+5YwVu",
	"gCtso5Rjte4n2kD/ZHIcIxP5ZvSe2MTR4WDUfvIiPCoi+ywsMDRdySJb7WTwwd08+3JLjtW19xA/oCAm",
	"6s9hnm2WJGu/kvR76B8O8/SaPneo/4uYAXXrvp3SKrUhbpto/Gc8Gh5yYcBORNuGreHq2WnHcLXbrH5q",
	"9ZdpU036X6XIX15X/+vL6qa39dqV44auQmra7yviE/eUNHvyaRHSMIUirDh1FzGGtrA+rnOjs3xrAOU0",
	"k3ouaOC4oIKndKsVDK7UZuYka6tMfZR6Rdz+ibqP0f7GHqFRiIxXDszgIYfEYaVNdJbxvgXcCA9nd0or",
	"uMPKVo5rqbiR9r7RqzZBY1k/sQVgNweXCxSlvzztZ4V0IpfQDzv2ace6dlzobCqUbymPfD+PVQpSlLr6",
	"pRy3PeSSpkgzLi10+9v2Zdx+Wn/YzdL2VKbjfumxm6KQt05oLPiK3qK6i9p7UOua9qmz/sS7420vLMf5",
	"jdAqLxpCUMTs1y9X10yoRBZEU4Hdea+5YyF71vJV89RDLB5ef62lW3eImVAj/9ZJl8G3B3P8awFlevX3",
	"+eWlRMVuSziqnPnlcsS43aXUmDPK/O5pumNXP3/+8sv7JgW9yQ0sMRVeXF1+ZNw57LNfOjY6OY5PTo9e",
	"kb+fAQdkU0jr2lLTwB6qlQkn5twhSrnk66BYnX0qxvpSovpJqwQ+aQdlqsm0ad1F2r0wKHzz9WXsvbCo",
	"mm8ffE0Kl2M5n8N21KAnnh2fdl3yl35UvuDrDW0hZltTR99l+diIPS1tLLcLXci0dkz6LqXc1ReUajjP",
	"Z+igZeM6K6TcHr2O1faU6LEe6t3cIkS2yDJu1t2lGTMNn9OomY6OmkMmFwaWubYdc62RtQV8riebPh+A",
	"dT/qdO2/CFKuHNg2xpiDh/5qteqjB/QLI0FhZ5nWX2jRQQo+z0iZ53eZrW81MFQOTPh7vvbY3HqW0+Vp",
	"exT83fqRaq1P+zONVm95UCfd+FRt02sy+eELW45m7j97d3zcO4A+Iwb0fcUzJG99kdH8yOQ5DQVr0nTh",
	"LEvFbAYGQzgQaqYVNNoGTCmv/Yql12wHn9MFbn/i0sGRy0nUphe9fZUnVVPeP1Ryz+0getPOaHLHPD8X",
	"GVd9AzzlUwnMwYPzVSY3eilSsDtpnfGpLkqSHj7CevJrOL/q9gDwfuRp9XUeAXjyPwCfBWDnRRmbcSGx",
	"Ufms5Lr8aKd9I3vXuCreLTqtC7rtwtO44qpqW1fleaqS9R5bt2jlEfR9g2/S6kugHZ5NZaB9ScT9bU+c",
	"gAMVz8yA5yLCLUuhdqd6a7cQat78fobUqgmLV2Nzu/lXAAAA///qeZVaeiwAAA==",
}

// GetSwagger returns the content of the embedded swagger specification file
// or error if failed to decode
func decodeSpec() ([]byte, error) {
	zipped, err := base64.StdEncoding.DecodeString(strings.Join(swaggerSpec, ""))
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr, err := gzip.NewReader(bytes.NewReader(zipped))
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}
	var buf bytes.Buffer
	_, err = buf.ReadFrom(zr)
	if err != nil {
		return nil, fmt.Errorf("error decompressing spec: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cached of a decoded swagger spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSwagger returns the Swagger specification corresponding to the generated code
// in this file. The external references of Swagger specification are resolved.
// The logic of resolving external references is tightly connected to "import-mapping" feature.
// Externally referenced files must be embedded in the corresponding golang packages.
// Urls can be supported but this task was out of the scope.
func GetSwagger() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}
