openapi: "3.0.3"
info:
  title: OpenAPI - CETEN Accounts
  version: "0.1.0"
  license:
    name: MIT
    url: https://opensource.org/license/mit/
servers:
  - url: http://localhost:8080
  - url: https://account.ceten.fr/api
paths:
  /health:
    get:
      responses:
        "200":
          description: "API Online"
